---
- hosts: metrics.service.cassandra
  vars:
  user: ubuntu
  sudo: True
  tasks:
  - name: add cassandra deb
    action: shell echo "deb http://www.apache.org/dist/cassandra/debian 11x main\ndeb-src http://www.apache.org/dist/cassandra/debian 11x main" > /etc/apt/sources.list.d/cassandra.list
  - name: get cassandra deb keys
    action: command gpg --keyserver pgp.mit.edu --recv-keys $item 
    with_items:
      - F758CE318D77295D
      - 2B5C1B00 
  - name: install cassandra deb keys
    action: shell gpg --export --armor $item | apt-key add -
    with_items:
      - F758CE318D77295D
      - 2B5C1B00 
  - name: update apt for cassandra
    action: command apt-get -y update
  - name: install cassandra
    action: command apt-get -y install cassandra
    notify:
    - restart cassandra
  - name: install cassandra configuration
    action: copy src=cassandra.yaml dest=/etc/cassandra/cassandra.yaml mode=644
  - name: update directory permissions
    action: file path=/var/db/cassandra owner=cassandra group=cassandra state=directory
  handlers:
  - name: restart cassandra
    action: service name=cassandra state=restarted


